### ISSUE TITLE
When to upgrade dependencies?

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-app#179]
There really isn't a clear answer as to when dependencies should be upgraded, and to what extent. For example, should they be upgraded for every major/minor/patch version release, and what kind of changes would be acceptable (i.e. `2.3.4 => 2.3.5` vs `2.3.4 => 2.4.0` vs `2.3.4 => 3.0.0`). This should be made clear in [CONTRIBUTING.md](https://github.com/alexa-js/alexa-app/blob/master/CONTRIBUTING.md).

Note that this issue is not limited to all the other alexa-js repositories.

**Comment by dblock** [comment]
The alexa-app package.json defines the compatible versions of dependencies, usually the minimal dependencies. So it should never be updated unless you have to use a newer version of a dependency because it introduced some new feature or fix that is required for this library.

This is pretty standard, not sure if it's needed in CONTRIBUTING, but feel free.

**Comment by dblock** [comment]
I think we should close this.
