### ISSUE TITLE
Should app.error() resolve?

### ISSUE THREAD

**Issue by rickwargo** [alexa-js/alexa-app#182]
If exceptions are caught in `app.error()`, should they be resolved? The example shows:

```
app.error = function(e, request, response) {
  response.say("I captured the exception! It was: " + e.message);
};
```
However it still ends up calling 
```response.fail("Unhandled exception.", e);```
because `(!response.resolved)`.

Either the example `app.error()` should resolve the request with `response.send();` or it should be called after executing `self.error(e, request, response)`.

Or am I misunderstanding how error capture should work in `app.error()`?

**Comment by dblock** [comment]
I think you're right. Try to write a test for this? 

Also look at https://github.com/alexa-js/alexa-app/pull/171, we want that merged soon, it may have fixed this problem or we should fix it there.

**Comment by rickwargo** [comment]
It doesn't appear fixed in #171. I think the default behavior should be to resolve by calling `response.send()` in the exception handler as the user error handler, `app.error()` can still explicitly fail if desired.

I'll write a test for this issue.

Also, in the failure block, e often contains a string and mot e.message and this should be part of the .fail() call, especially if it is an indexed message (self.messages[e]`).

**Comment by ajcrites** [comment]
According to the documentation we currently have it seems like having `app.error` should default to resolving errors as long as it is defined. I can update #171 to do this which would also allow (actually enforce) the error handler be asynchronous.

Actually #171 ends up funneling all errors to `response.fail` no matter what which gives `.post` an opportunity to be called. This obviates the need for `.error` since `.post` can handle errors on its own anyway. I understand that intuitively it would make sense to have a `.error` though.

Let me know what you guys think -- I can either remove `.error` entirely and have `.post` also be used for error handling or I can add it to the chain in #171.

**Comment by rickwargo** [comment]
I created pull request #183 to add tests for this problem. I also added the response.send() as a solution, along with updates to README. Added more tests for the unhandled exception strings (with the change suggested by @ajcrites). 

Not sure we should remove .error as that may be in use (functionality has been there since the inception).

**Comment by ajcrites** [comment]
`app.error` automatically resolves now unless you throw an error inside of it.
