### ISSUE TITLE
Reprompt User For Missing Slot Value

### ISSUE THREAD

**Issue by Archetype90** [alexa-js/alexa-app#307]
My goal is to have my skill re-prompt for the slot value if it is undefined or does not exist and then use that slot value in the existing skill. Does anyone have an example of this? Some details... 

For some reason, the number "2" is having problems with my skill. As a result, I was trying to build re-prompting logic in the event that the light or brightness is not picked up. 

```
app.intent('ChangeBrightnessIntent', {
  'slots': {
    'LIGHT': 'AMAZON.NUMBER',
    'BRIGHTNESS': 'AMAZON.NUMBER'
  },
  'utterances': [
    'change light {-|LIGHT} brightness to {-|BRIGHTNESS}'
  ]
},
  function (req, res) {
    const light = req.slot('LIGHT', false);
    var brightness = req.slot('BRIGHTNESS', false);

    if (!light) {
      const prompt = 'Tell me a valid light number.';
      res.say(prompt).shouldEndSession(false);
    } else if (!brightness) {
      const prompt = 'Tell me a valid brightness 0 to 254.';
      res.say(prompt).shouldEndSession(false);
    } else {
      console.log("Changing Light " + light + " brightness to " + brightness);
   }
});
```

So you can see a user asks Alexa "Alexa, ask bridge to change light 2 brightness to 0". This fails every time (although not for any other number), at which point the skill asks "Tell me a valid light number." I say the number "2", and it fires a different intent of mine, which has no utterances even close to two.

**Comment by lazerwalker** [comment]
There are two different approaches you can take:

1. If you’re using the new Skill Builder Beta on the Amazon side, it supports “Dialogs”, which are (among other things) intents that automatically reprompt as appropriate until all slots that have been marked as required have been filled. I could be incorrect, but I don’t believe this library has proper support for that yet. 

2. Create a separate intent that only matches when you say a number, specifically for reprompting purposes. You’ll need to make sure you’re doing a decent job of manual state tracking, so that when that intent is fired, you know it’s because you previously asked the user to specify a brightness, or whatever other user flow paths might have led there.

(1) seems like it’d be a cleaner fit for what you’re doing here specifically, but, as I said, i’m actually not sure if we handle this correctly yet, as it’s a relatively new set of functionality from Amazon. 

Hope that helps!

**Comment by Archetype90** [comment]
Thanks a lot for the reply! 

I actually ended up swapping over the the official Amazon NodeJS SDK and using the Dialogs, as you suggested. They are a fairly incredible feature - hopefully this library will have full support for them soon.
