### ISSUE TITLE
Dynamically slots values

### ISSUE THREAD

**Issue by unixconky** [alexa-js/alexa-app#350]
I have a skill that looks up property management information for apartment buildings. We have over 150 properties which are defined as values for a slot. 4 digit property numbers for values and string property names as synonyms.

I would like to be able to query a database for the slot values and synonyms dynamically at runtime. Is this currently possible?

https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/33499096-dynamic-slot-values

**Comment by lazerwalker** [comment]
That's not currently possible due to limitations in the Alexa Skills Kit. If you want to provide those slot values and synonyms to Amazon, you need to do it ahead of time.

That said, it's possible using this library to automate the process of programmatically generating that list and uploading it to Amazon via ask-cli. Depending on how frequently that list updates, you could easily set up a cron job to run once an hour/day/week/etc that generates and sends the latest slots and synonyms to Amazon.

**Comment by lazerwalker** [comment]
Closing this out for now — feel free to reopen or comment if you have specific questions.
