### ISSUE TITLE
The schema generated from the number example doesn't work

### ISSUE THREAD

**Issue by dblock** [alexa-js/alexa-app#89]
```js
app.intent('StartIntent', {
        "slots": {
            "number" : "NUMBER"
        },
        "utterances": [
            "start {1-100|number}"
        ]
    },
```

This generates utterances:

```
StartIntent	start {one|number}
StartIntent	start {two|number}
StartIntent	start {three|number}
```

This doesn't work in sample utterances.

```
Error: There was a problem with your request: Incorrect syntax: A value may not be supplied for the slot 'number'. Occurred in sample 'StartIntent	start {one|number}' on line 4. 
```

**Comment by dblock** [comment]
@fremail Interested in picking this one up?

**Comment by fremail** [comment]
@dblock Sorry, I don't have time to work on this :(

**Comment by mittermayr** [comment]
Reason why it does not work is explained here: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/migrating-to-the-improved-built-in-and-custom-slot-types

... and basically says: it doesn't need (allow!) multiple examples for numbers anymore. So instead of generating (Assume 'count' is AMAZON.NUMBER):

```
please give me {one|count} apple
please give me {two|count} apple
please give me {three|count} apple
```

you would now simply be allowed to specify:

`please give me {count} apple`

(which sort of makes me wonder how you can restrict to number ranges, but okay).

**Comment by dblock** [comment]
@mittermayr Would appreciate a verified PR fixing the README for this and possibly other cases.
